export const Truth = [
    'Lần cuối cùng bạn nói dối là khi nào?',
    'Lần cuối cùng bạn khóc là khi nào?',
    'Nỗi sợ hãi lớn nhất của bạn là gì?',
    'Tưởng tượng lớn nhất của bạn là gì?',
    'Ai là người cuối cùng bạn tìm kiếm trên Facebook?',
    'Điều kỳ lạ nhất bạn từng ăn là gì?',
    'Yếu tố phá vỡ mối quan hệ của bạn là gì?',
    'Bí mật mà bạn chưa bao giờ nói với ai là gì?',
    'Bạn có một tài năng tiềm ẩn?',
    'Ai là người nổi tiếng đầu tiên của bạn?',
    'Bạn đã bao giờ gian lận trong một kỳ thi?',
    'Nếu bạn tham gia một chương trình truyền hình thực tế, đó sẽ là chương trình nào?',
    'Sự bất an lớn nhất của bạn là gì?',
    'Sai lầm lớn nhất mà bạn từng mắc phải là gì?',
    'Một điều bạn ghét mọi người biết về bạn là gì?',
    'Điều tồi tệ nhất mà bất cứ ai từng làm với bạn là gì?',
    'Điều tốt nhất mà bất cứ ai từng làm cho bạn là gì?',
    'Thói quen tồi tệ nhất của bạn là gì?',
    'Quan niệm sai lầm lớn nhất về bạn là gì?',
    'Một điều bạn muốn mọi người biết về bạn là gì?',
    'Tại sao mối quan hệ cuối cùng của bạn tan vỡ?',
    'Lời khuyên tốt nhất mà bạn nhận được là gì?',
    'Số tiền nhiều nhất bạn đã chi tiêu cho một đêm đi chơi là gì?',
    'Bạn đã bao giờ trả lại hoặc tặng lại một món quà chưa?',
    'Bạn có một anh chị em yêu thích?',
    'Bạn đã mua gì mà là sự lãng phí tiền bạc lớn nhất?',
    'Bạn đánh giá ngoại hình của mình trên thang điểm từ 1 đến 10 như thế nào?',
    'Bạn ngưỡng mộ người nổi tiếng nào?',
    'Nếu bạn có thể là một người nổi tiếng trong một ngày, đó sẽ là ai?',
    'Nếu bạn có thể làm bất kỳ công việc nào trên thế giới, nó sẽ là gì?',
    'Cuộc sống mơ ước của bạn là gì?',
    'Bạn coi trọng điều gì nhất - tiền bạc, danh tiếng, thành công, bạn bè, gia đình, v.v.?',
    'Lá cờ đỏ lớn nhất của bạn là gì?',
    'Một bộ phim mà bạn xấu hổ khi thừa nhận bạn thích là gì?',
    'Bạn thầm nghĩ nghệ sĩ âm nhạc nào được đánh giá quá cao?',
    'Ý kiến chính trị gây tranh cãi nhất của bạn là gì?',
    'Đặt tên cho một cái gì đó bạn không thể sống thiếu',
    'Bạn nghĩ bạn sẽ ở đâu trong thời gian năm năm?',
    'Bạn nghĩ mình sẽ làm tốt như thế nào trong một bộ phim kinh dị?',
    'Bạn sở hữu bao nhiêu thú nhồi bông?',
    'Bạn đã bao giờ gặp rắc rối ở trường chưa? Và nếu có thì để làm gì?',
    'Bạn có nỗi ám ảnh nào không?'
]

export const Dare = [
    'Cố gắng tung hứng 3 vật mà nhóm lựa chọn',
    'Hiển thị ảnh xấu hổ nhất trên điện thoại của bạn',
    'Hiển thị năm người cuối cùng bạn đã nhắn tin và nội dung tin nhắn',
    'Hãy để những người còn lại trong nhóm gửi tin nhắn trực tiếp cho ai đó từ tài khoản Facebook của bạn',
    'Thực hiện 100 lần squats',
    'Hãy để nhóm xem trong DM Facebook của bạn',
    'Hiển thị cho chúng tôi báo cáo thời gian sử dụng thiết bị của bạn',
    'Giữ ba viên đá trong miệng cho đến khi chúng tan chảy',
    'Hét lên từ đầu tiên xuất hiện trong đầu bạn',
    'Nhắm mắt lại cho đến khi đến lượt bạn',
    'Cho mọi người xem trong ví có gì',
    'Bắt chước người bên phải bạn trong 10 phút',
    'Ăn gì đó mà không cần sử dụng tay của bạn',
    'Thì thầm một bí mật với người bên trái của bạn',
    'Nói hai điều trung thực về những người khác trong nhóm',
    'Kể câu chuyện buồn nhất mà bạn biết',
    'Giữ đồ uống của bạn bằng hai tay trong phần còn lại của buổi tối',
    'Nói có với mọi thứ trong 1 phút tiếp theo',
    'Hiển thị hình ảnh yêu thích của bạn về bản thân',
    'Thực hiện 50 lần chống đẩy',
    'Tiết lộ những gì bạn nghĩ mọi người trong nhóm sẽ đạt được trong thời gian năm năm',
    'Hãy dành cho mọi người trong phòng một lời khen ',
    'Hãy để nhóm tạo kiểu tóc của bạn và để nó như vậy trong toàn bộ trò chơi',
    'Chỉ nói thì thầm trong 10 phút tiếp theo',
    'Nói một bí mật về ai đó trong phòng nhưng không tiết lộ tên của họ',
    'Giữ 1 tay trên người của người bên phải',
    'Trong vòng 3 phút chỉ giao tiếp bằng tiếng sủa',
    'Kể cho mọi người nghe một câu chuyện xấu hổ về bản than',
    'Ngồi trong góc tự kỉ trong 5 phút',
    'Cởi một món đồ trên người',
]

export default 0;